//
// Created by Wesley Klop on 15/04/2021.
//

#ifndef BALANCINGROBOT_STEPRESOLUTION_H
#define BALANCINGROBOT_STEPRESOLUTION_H

enum StepResolution {
    FULL,
    HALF,
    QUARTER,
    EIGHTH,
    SIXTEENTH,
};

#endif //BALANCINGROBOT_STEPRESOLUTION_H
