#ifndef BALANCINGROBOT_CONSTANTS_H
#define BALANCINGROBOT_CONSTANTS_H

#define APP_BAUD_RATE 115200

#define MOTOR1_STEP_PIN 2
#define MOTOR1_DIR_PIN 3
#define MOTOR2_STEP_PIN 4
#define MOTOR2_DIR_PIN 5
#define MOTOR1_MS1_PIN 6
#define MOTOR1_MS2_PIN 7
#define MOTOR1_MS3_PIN 8
#define MOTOR2_MS1_PIN 9
#define MOTOR2_MS2_PIN 10
#define MOTOR2_MS3_PIN 11
#define TUNE_PIN A2

#define MOTOR_SPEED_LOWER 1500
#define MOTOR_SPEED_UPPER 50

#define MOTOR_STEPS_PER_ROTATION 200
#define MICROSECONDS_PER_MINUTE 60000000UL

#endif //BALANCINGROBOT_CONSTANTS_H
